### ISSUE TITLE
junit vs OUnitLoggerJUnit

### ISSUE THREAD

**Issue by gildor478** [Khady/ocaml-junit#1]
Hi,

I am the author of OUnit. I wonder what is the difference in between junit and the internal JUnit logger in OUnit:
https://github.com/gildor478/ounit/blob/master/src/lib/ounit2/advanced/oUnitLoggerJUnit.ml

I would be interested if there is any bug in the internal reporter to fix them.

**Comment by Khady** [comment]
First, thank you for ounit! it's still my go to test framework.

When I started junit, the goal was not to have a direct integration with the test frameworks. I wrote it to generate some junit reports from a "normal" program, not a test suite. I was aware of OUnitLoggerJUnit, but it seemed complicated to use it directly. The integration with ounit was written later, mostly by @c-cube who could probably explain better why he did it.

One thing that I can report is that many people are not aware of ounit ability to export a junit report. And they end up using an external tool, because they don't dig enough in ounit's documentation. But I am not aware of a bug in OUnitLoggerJUnit.

**Comment by c-cube** [comment]
Oh boy, it's been a long time. I wrote that junit/ounit bridge because I wasn't aware, I think, that OUnit could already do that (tbh, I don't remember if there were online docs for ounit). My use case was to feed test reports to jenkins, if I remember correctly.

**Comment by gildor478** [comment]
I think I created it circa 2013 but might have not done a good job at promoting it. It was used for a long time on my own Jenkins instance.

I should probably work more on the doc when doing this type of thing.

Feel free to close the bug, this one is on me -- I need to improve OUnit doc.
